media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /media/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /
